### ISSUE TITLE
Cant use fixed VA for create Invoice

### ISSUE THREAD

**Issue by cendekia** [xendit/xendit-php-clients#23]
createInvoice ($external_id, $amount, $payer_email, $description)

How i suppose to pass "callback_virtual_account_id" to make invoice payment using fixed VA?

**Comment by LieAlbertTriAdrian** [comment]
Hi Cendekia, Yea. It's not supported yet in this PHP library. Will update soon. Thanks for feedback!

**Comment by LieAlbertTriAdrian** [comment]
Hi @cendekia ,

Sorry for waiting a long time, now you can pass options to include `callback_virtual_account_id` when creating invoice on version 1.1.0. There is an example you could try in `README.md`

https://packagist.org/packages/xendit/xendit-php-clients#1.1.0

Best,
Albert

**Comment by cendekia** [comment]
Nicely done thank you @LieAlbertTriAdrian
